name: CI

on:
  push:
    branches:
      - master

env:
  REPO_NAME: ${{ github.event.repository.name }}
  BRANCH_NAME: ${{ github.ref_name }}
  DEPLOY_ADDRESS: ${{ secrets.DEPLOY_ADDRESS }}
  SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{env.DEPLOY_ADDRESS}}
          privateKey: ${{env.SSH_KEY}}
          command: |
            cd ah-apps

            if [ -d "$REPO_NAME" ]; then
              cd $REPO_NAME
              git pull
            else
              git clone https://github.com/spl33t/react-effector-vite-fsd-template
              cd $REPO_NAME
            fi
            
            docker-compose up